# action.yml
name: 'Evaluate'
description: 'Evaluate student solution to a PPR problem'
inputs:
  repo-name:  # name of repo
    description: 'Name of repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
